# Generated by Django 2.2.3 on 2019-08-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titanic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cabin',
        ),
    ]
